"""
ChartConfig ORM model.

Stores Plotly chart configurations generated by the VisualizerAgent.
Each chart is persisted as a JSON config that can be:
- Rendered directly by the frontend (Plotly.js)
- Downloaded as a static image via the export API
- Embedded in generated reports

Separating chart configs from the report allows the frontend to
render an interactive gallery without re-running the analysis.
"""

from __future__ import annotations

import uuid
from enum import Enum
from typing import Any

from sqlalchemy import ForeignKey, Integer, String
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin, UUIDPrimaryKeyMixin


class ChartType(str, Enum):
    BAR = "bar"
    LINE = "line"
    SCATTER = "scatter"
    HISTOGRAM = "histogram"
    BOX = "box"
    HEATMAP = "heatmap"
    PIE = "pie"
    VIOLIN = "violin"
    CORRELATION_MATRIX = "correlation_matrix"
    TIME_SERIES = "time_series"
    DISTRIBUTION = "distribution"
    CUSTOM = "custom"


class ChartConfig(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "chart_configs"

    # ── Foreign keys ──────────────────────────────────────────────────────────
    session_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("analysis_sessions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    agent_run_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("agent_runs.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # ── Identity ──────────────────────────────────────────────────────────────
    title: Mapped[str] = mapped_column(String(512), nullable=False)
    description: Mapped[str | None] = mapped_column(String(1024), nullable=True)
    chart_type: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        index=True,
    )

    # ── Chart data ────────────────────────────────────────────────────────────
    # Full Plotly figure dict: {data: [...], layout: {...}, config: {...}}
    plotly_config: Mapped[dict[str, Any]] = mapped_column(
        JSONB,
        nullable=False,
        comment="Complete Plotly figure specification for frontend rendering",
    )

    # Columns from the dataset this chart visualizes
    columns_used: Mapped[list[str]] = mapped_column(
        JSONB,
        nullable=False,
        default=list,
    )

    # Insight this chart supports (from AnalystAgent)
    insight_context: Mapped[str | None] = mapped_column(
        String(1024),
        nullable=True,
        comment="Why the VisualizerAgent chose this chart",
    )

    # ── Display ordering ──────────────────────────────────────────────────────
    display_order: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        comment="Order in which charts are shown in the gallery",
    )

    # ── Storage reference (for exported static image) ─────────────────────────
    image_file_key: Mapped[str | None] = mapped_column(
        String(1024),
        nullable=True,
        comment="Storage key for pre-rendered PNG/SVG export",
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    session: Mapped["AnalysisSession"] = relationship(  # noqa: F821
        "AnalysisSession",
        back_populates="chart_configs",
        lazy="select",
    )

    def __repr__(self) -> str:
        return (
            f"<ChartConfig id={self.id} type={self.chart_type} "
            f"title={self.title!r}>"
        )
