/**
 * ReportPage — executive intelligence report generated by StorytellerAgent.
 * Narrative blocks + recommendations + key takeaways + chart thumbnails.
 */
import { useParams, Link, useNavigate } from "react-router-dom";
import {
  FileText, ChevronRight, BarChart3, Lightbulb,
  ArrowRight, Star, AlertCircle, CheckCircle2, Zap,
  BookOpen, Target, Sparkles
} from "lucide-react";
import { PageHeader }     from "@/components/ui/PageHeader";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/Card";
import { Button }         from "@/components/ui/Button";
import { Badge }          from "@/components/ui/Badge";
import { SkeletonCard }   from "@/components/ui/Skeleton";
import { EmptyState }     from "@/components/ui/EmptyState";
import { useReport }      from "@/hooks/useReport";
import { formatDate, cn } from "@/lib/utils";
import type { NarrativeBlock, Recommendation, Insight } from "@/types";

// ── Priority colours ──────────────────────────────────────────────
function priorityVariant(p: string): "danger" | "warning" | "default" {
  return p === "high" ? "danger" : p === "medium" ? "warning" : "default";
}

function importanceVariant(i: string): "danger" | "warning" | "default" {
  return i === "high" ? "danger" : i === "medium" ? "warning" : "default";
}

// ── Narrative block ───────────────────────────────────────────────
function NarrativeBlockCard({ block }: { block: NarrativeBlock }) {
  const icons: Record<string, typeof BookOpen> = {
    intro:          Sparkles,
    finding:        Lightbulb,
    recommendation: Target,
    conclusion:     CheckCircle2,
  };
  const Icon = icons[block.block_type] ?? BookOpen;

  return (
    <div className="flex gap-4">
      <div className="flex flex-col items-center gap-1 shrink-0">
        <div className={cn(
          "w-8 h-8 rounded-lg flex items-center justify-center border",
          block.importance === "high"   ? "bg-warning/10 border-warning/30 text-warning" :
          block.importance === "medium" ? "bg-brand-500/10 border-brand-500/30 text-brand-400" :
          "bg-surface-3 border-surface-4 text-zinc-500"
        )}>
          <Icon className="w-3.5 h-3.5" />
        </div>
        <div className="w-px flex-1 bg-surface-4" />
      </div>
      <div className="flex-1 pb-6">
        <div className="flex items-center gap-2 mb-2">
          <h3 className="text-sm font-semibold text-zinc-100">{block.heading}</h3>
          <Badge variant={importanceVariant(block.importance)} className="text-2xs">
            {block.importance}
          </Badge>
        </div>
        <p className="text-sm text-zinc-400 leading-relaxed">{block.content}</p>
      </div>
    </div>
  );
}

// ── Recommendation card ───────────────────────────────────────────
function RecommendationCard({ rec, index }: { rec: Recommendation; index: number }) {
  return (
    <div className="card p-4 space-y-3">
      <div className="flex items-start justify-between gap-2">
        <div className="flex items-center gap-2.5">
          <span className="flex items-center justify-center w-6 h-6 rounded-full bg-brand-500/15 border border-brand-500/30 text-brand-400 text-xs font-bold shrink-0">
            {index + 1}
          </span>
          <h4 className="text-sm font-semibold text-zinc-100">{rec.title}</h4>
        </div>
        <Badge variant={priorityVariant(rec.priority)}>{rec.priority}</Badge>
      </div>

      <div className="space-y-2 pl-9">
        <div>
          <p className="text-2xs font-medium text-zinc-500 uppercase tracking-wide mb-1">Action</p>
          <p className="text-sm text-zinc-300">{rec.action}</p>
        </div>
        <div>
          <p className="text-2xs font-medium text-zinc-500 uppercase tracking-wide mb-1">Rationale</p>
          <p className="text-xs text-zinc-400 leading-relaxed">{rec.rationale}</p>
        </div>
        <div className="flex items-center gap-1.5 text-xs text-success">
          <Zap className="w-3 h-3" />
          <span>{rec.expected_impact}</span>
        </div>
      </div>
    </div>
  );
}

// ── Insight chip ──────────────────────────────────────────────────
function InsightChip({ insight }: { insight: Insight }) {
  return (
    <div className="card p-3 space-y-1.5">
      <div className="flex items-center justify-between gap-2">
        <span className="text-2xs font-mono text-zinc-600 uppercase">{insight.category}</span>
        <Badge variant={importanceVariant(insight.importance)} className="text-2xs">
          {insight.importance}
        </Badge>
      </div>
      <p className="text-xs font-medium text-zinc-200">{insight.title}</p>
      <p className="text-2xs text-zinc-500 leading-relaxed line-clamp-3">{insight.description}</p>
      <div className="flex items-center gap-1.5">
        <div
          className="h-1 rounded-full bg-brand-500/30 flex-1"
          title={`Confidence: ${Math.round(insight.confidence * 100)}%`}
        >
          <div
            className="h-1 rounded-full bg-brand-500"
            style={{ width: `${insight.confidence * 100}%` }}
          />
        </div>
        <span className="text-2xs text-zinc-600">{Math.round(insight.confidence * 100)}%</span>
      </div>
    </div>
  );
}

// ── Page ──────────────────────────────────────────────────────────
export function ReportPage() {
  const { sessionId } = useParams<{ sessionId: string }>();
  const navigate      = useNavigate();
  const { data: report, isLoading } = useReport(sessionId);

  if (isLoading) {
    return (
      <div className="space-y-4">
        {[...Array(5)].map((_, i) => <SkeletonCard key={i} />)}
      </div>
    );
  }

  if (!report) {
    return (
      <EmptyState
        icon={FileText}
        title="Report not available"
        description="The StorytellerAgent hasn't generated the report yet. Wait for the analysis to complete."
        action={{ label: "Back to Timeline", onClick: () => navigate(`/session/${sessionId}/timeline`) }}
      />
    );
  }

  return (
    <div className="max-w-4xl mx-auto space-y-6 animate-fade-in">
      <PageHeader
        title={report.title}
        description={`Generated ${formatDate(report.created_at)}`}
        breadcrumb={
          <span className="flex items-center gap-1">
            <Link to="/dashboard" className="hover:text-zinc-300">Dashboard</Link>
            <ChevronRight className="w-3 h-3" />
            <Link to={`/session/${sessionId}/timeline`} className="hover:text-zinc-300">Timeline</Link>
          </span>
        }
        actions={
          <Button variant="outline" size="sm" onClick={() => navigate(`/session/${sessionId}/visualizations`)}>
            <BarChart3 className="w-3.5 h-3.5" />
            View Charts
          </Button>
        }
      />

      {/* Executive summary */}
      <Card className="border-brand-500/20 bg-brand-500/5">
        <CardHeader>
          <div className="flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-brand-400" />
            <CardTitle>Executive Summary</CardTitle>
          </div>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-zinc-300 leading-relaxed">{report.executive_summary}</p>
        </CardContent>
      </Card>

      {/* Key takeaways */}
      {report.recommendations?.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Star className="w-4 h-4 text-warning" />
              Key Takeaways
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-2">
              {(report.recommendations as unknown as { expected_impact?: string }[])
                .slice(0, 5)
                .map((rec, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm text-zinc-300">
                    <ArrowRight className="w-3.5 h-3.5 text-brand-400 mt-0.5 shrink-0" />
                    {rec.expected_impact ?? JSON.stringify(rec)}
                  </li>
                ))}
            </ul>
          </CardContent>
        </Card>
      )}

      {/* Narrative */}
      {report.narrative_json?.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <BookOpen className="w-4 h-4 text-zinc-400" />
              Detailed Analysis
            </CardTitle>
            <CardDescription>{report.narrative_json.length} sections</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-0">
              {report.narrative_json.map((block, i) => (
                <NarrativeBlockCard key={i} block={block} />
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Recommendations */}
      {report.recommendations_json?.length > 0 && (
        <div>
          <h2 className="text-sm font-semibold text-zinc-100 mb-3 flex items-center gap-2">
            <Target className="w-4 h-4 text-brand-400" />
            Recommendations
          </h2>
          <div className="space-y-3">
            {report.recommendations_json.map((rec, i) => (
              <RecommendationCard key={i} rec={rec} index={i} />
            ))}
          </div>
        </div>
      )}

      {/* Insights grid */}
      {report.insights_json?.length > 0 && (
        <div>
          <h2 className="text-sm font-semibold text-zinc-100 mb-3 flex items-center gap-2">
            <Lightbulb className="w-4 h-4 text-warning" />
            All Insights
            <span className="text-xs text-zinc-500 font-normal">({report.insights_json.length})</span>
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
            {report.insights_json.map((insight, i) => (
              <InsightChip key={i} insight={insight} />
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
