/**
 * VisualizationPage — gallery of AI-generated Plotly charts.
 * Each chart was autonomously selected and generated by the VisualizerAgent.
 */
import { useState } from "react";
import { useParams, Link, useNavigate } from "react-router-dom";
import {
  BarChart3, ChevronRight, FileText, Info,
  Columns, LayoutGrid
} from "lucide-react";
import Plot from "react-plotly.js";
import { PageHeader }     from "@/components/ui/PageHeader";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/Card";
import { Button }         from "@/components/ui/Button";
import { Badge }          from "@/components/ui/Badge";
import { SkeletonCard }   from "@/components/ui/Skeleton";
import { EmptyState }     from "@/components/ui/EmptyState";
import { useReport }      from "@/hooks/useReport";
import { useSession }     from "@/hooks/useAnalysis";
import { cn }             from "@/lib/utils";
import type { PlotlyChartSpec } from "@/types";

// ── Chart type badge variant ───────────────────────────────────────
function chartVariant(type: string) {
  const map: Record<string, "brand" | "success" | "info" | "warning" | "default"> = {
    bar:               "brand",
    histogram:         "info",
    scatter:           "success",
    correlation_matrix:"warning",
    time_series:       "brand",
    box:               "default",
  };
  return map[type] ?? "default";
}

// ── Single chart card ─────────────────────────────────────────────
function ChartCard({ chart }: { chart: PlotlyChartSpec }) {
  const [showInfo, setShowInfo] = useState(false);

  return (
    <Card className="flex flex-col overflow-hidden">
      <CardHeader>
        <div className="flex items-start justify-between gap-2">
          <div className="min-w-0">
            <CardTitle className="truncate">{chart.title}</CardTitle>
            <CardDescription className="line-clamp-2 mt-0.5">{chart.description}</CardDescription>
          </div>
          <div className="flex items-center gap-1.5 shrink-0">
            <Badge variant={chartVariant(chart.chart_type)}>
              {chart.chart_type.replace("_", " ")}
            </Badge>
            <button
              className="text-zinc-600 hover:text-zinc-400 transition-colors"
              onClick={() => setShowInfo(v => !v)}
              title="Chart info"
            >
              <Info className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>
      </CardHeader>

      <CardContent className="flex-1 pt-0">
        {/* Info panel */}
        {showInfo && (
          <div className="mb-3 p-3 rounded-lg bg-surface-3/50 border border-surface-4 space-y-1.5">
            <p className="text-2xs text-zinc-500">
              <span className="text-zinc-400 font-medium">Columns: </span>
              {chart.columns_used.join(", ")}
            </p>
            {chart.insight_context && (
              <p className="text-2xs text-zinc-500">
                <span className="text-zinc-400 font-medium">Supports: </span>
                {chart.insight_context}
              </p>
            )}
          </div>
        )}

        {/* Plotly chart */}
        <div className="plotly-chart w-full">
          <Plot
            data={chart.plotly_figure.data as Plotly.Data[]}
            layout={{
              ...(chart.plotly_figure.layout as Partial<Plotly.Layout>),
              autosize: true,
              height: 300,
              margin: { t: 40, r: 16, b: 48, l: 56 },
            }}
            config={{
              displayModeBar: true,
              modeBarButtonsToRemove: ["lasso2d", "select2d"],
              displaylogo: false,
              responsive: true,
            }}
            style={{ width: "100%", height: "300px" }}
            useResizeHandler
          />
        </div>

        {/* Column pills */}
        <div className="flex flex-wrap gap-1 mt-3">
          {chart.columns_used.map((col) => (
            <span key={col} className="px-1.5 py-0.5 text-2xs rounded font-mono bg-surface-3 border border-surface-4 text-zinc-500">
              {col}
            </span>
          ))}
        </div>
      </CardContent>
    </Card>
  );
}

// ── Page ──────────────────────────────────────────────────────────
export function VisualizationPage() {
  const { sessionId } = useParams<{ sessionId: string }>();
  const navigate = useNavigate();
  const [layout, setLayout] = useState<"grid" | "single">("grid");

  const { data: report, isLoading } = useReport(sessionId);
  const { data: session }           = useSession(sessionId);

  if (isLoading) {
    return (
      <div className="space-y-4">
        <SkeletonCard />
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
          {[...Array(4)].map((_, i) => <SkeletonCard key={i} />)}
        </div>
      </div>
    );
  }

  const charts = report?.charts ?? [];

  return (
    <div className="space-y-6 animate-fade-in">
      <PageHeader
        title="Visualizations"
        description={`${charts.length} charts generated by the VisualizerAgent`}
        breadcrumb={
          <span className="flex items-center gap-1">
            <Link to="/dashboard" className="hover:text-zinc-300">Dashboard</Link>
            <ChevronRight className="w-3 h-3" />
            <Link to={`/session/${sessionId}/timeline`} className="hover:text-zinc-300">Timeline</Link>
          </span>
        }
        actions={
          <div className="flex items-center gap-2">
            <div className="flex items-center border border-surface-4 rounded-lg overflow-hidden">
              <button
                className={cn("p-2 transition-colors", layout === "grid" ? "bg-surface-3 text-zinc-200" : "text-zinc-500 hover:text-zinc-300")}
                onClick={() => setLayout("grid")}
                title="Grid view"
              >
                <LayoutGrid className="w-3.5 h-3.5" />
              </button>
              <button
                className={cn("p-2 transition-colors", layout === "single" ? "bg-surface-3 text-zinc-200" : "text-zinc-500 hover:text-zinc-300")}
                onClick={() => setLayout("single")}
                title="Single column"
              >
                <Columns className="w-3.5 h-3.5" />
              </button>
            </div>
            <Button size="sm" onClick={() => navigate(`/session/${sessionId}/report`)}>
              <FileText className="w-3.5 h-3.5" />
              Full Report
            </Button>
          </div>
        }
      />

      {charts.length === 0 ? (
        <EmptyState
          icon={BarChart3}
          title="No visualizations yet"
          description="The VisualizerAgent hasn't generated charts yet. Wait for the analysis to complete."
          action={{ label: "Back to Timeline", onClick: () => navigate(`/session/${sessionId}/timeline`) }}
        />
      ) : (
        <div className={cn(
          "gap-4",
          layout === "grid"
            ? "grid grid-cols-1 lg:grid-cols-2"
            : "grid grid-cols-1 max-w-3xl mx-auto"
        )}>
          {charts.map((chart, i) => (
            <ChartCard key={i} chart={chart} />
          ))}
        </div>
      )}
    </div>
  );
}
